let currentUser=null, selected=null;
const users={estudiante:{role:'Estudiante',name:'Julio Cesar Lloclli'},colaborador:{role:'Colaborador',name:'Operador de comedor'},admin:{role:'Administrador',name:'Administrador'}};
function tickets(){return JSON.parse(localStorage.getItem('comedorTickets')||'[]')}function save(x){localStorage.setItem('comedorTickets',JSON.stringify(x))}
function login(){let u=username.value.trim(),p=password.value;if(!users[u]||p!=='123456'){loginMsg.textContent='Credenciales incorrectas.';return}currentUser=users[u];loginView.classList.add('hidden');logout.classList.remove('hidden');userInfo.textContent=currentUser.name+' — '+currentUser.role;if(u==='estudiante')studentView.classList.remove('hidden');if(u==='colaborador')staffView.classList.remove('hidden');if(u==='admin'){adminView.classList.remove('hidden');renderAdmin()}}
logout.onclick=()=>location.reload();
function generateTicket(){let list=tickets(),today=new Date().toISOString().slice(0,10);if(list.some(x=>x.code===code.value&&x.date===today)){ticketMsg.textContent='Ya existe una reserva para hoy.';return}let t={id:'TICKET-'+code.value+'-'+new Date().getFullYear()+'-'+Date.now().toString().slice(-4),code:code.value,name:name.value,turn:document.querySelector('input[name=turn]:checked').value,diet:diet.value,date:today,status:'VÁLIDO - SIN SERVIR'};list.push(t);save(list);ticketMsg.textContent='Ticket generado correctamente.';ticketBox.innerHTML='<h3>Ticket de comedor</h3><b>'+t.id+'</b><p>'+t.name+'</p><p>'+t.turn+'</p><p>Estado: '+t.status+'</p>';ticketBox.classList.remove('hidden')}
function validateTicket(){let t=tickets().find(x=>x.id===ticketInput.value.trim());result.innerHTML='';accessMsg.textContent='';serveBtn.classList.add('hidden');if(!t){accessMsg.textContent='Ticket no encontrado.';return}selected=t.id;result.innerHTML=`<tr><td>${t.code}</td><td>${t.name}</td><td>${t.turn}</td><td>${t.status}</td></tr>`;if(t.status==='VÁLIDO - SIN SERVIR'){accessMsg.textContent='✓ CONTROL DE ACCESO EXITOSO: permita el ingreso del comensal y entregue la bandeja.';serveBtn.classList.remove('hidden')}else accessMsg.textContent='Este ticket ya fue atendido; no puede usarse nuevamente.'}
function serveTicket(){let l=tickets(),t=l.find(x=>x.id===selected);t.status='ATENDIDO / SERVIDO';save(l);validateTicket();accessMsg.textContent='✓ Atención registrada correctamente.'}
function renderAdmin(){adminRows.innerHTML=tickets().map(t=>`<tr><td>${t.id}</td><td>${t.name}</td><td>${t.turn}</td><td>${t.diet}</td><td>${t.status}</td></tr>`).join('')||'<tr><td colspan="5">No hay reservas.</td></tr>'}function clearData(){localStorage.removeItem('comedorTickets');renderAdmin()}
